rk3288 & rk3399: vpu: set eos flag when the encoder get NULL frame
The CTS test will send NULL frame instead of eos flag, error log as follows:
junit.framework.AssertionFailedError: expected 30 frames, only decoded 31

Change-Id: I44a2b46401a980c7224d878292b286d03fd47560
Signed-off-by: Chen Jinsen <kevin.chen@rock-chips.com>

Former-commit-id: e0e3a0a51d175f2ebdfd871c87399794abe685a9